# See default detekt configuration here:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 4
  ParameterListWrapping:
    indentSize: 4
  NoBlankLineBeforeRbrace:
    active: false
    autoCorrect: false

style:
  ReturnCount:
    max: 5
  UnusedPrivateMember:
    allowedNames: premainArguments
